name: Makefile CI Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: install ndiff
      run:  curl -s -O ftp://ftp.math.utah.edu/pub/misc/ndiff-2.00.tar.gz && tar -xzf ndiff-2.00.tar.gz && cd ndiff-2.00 && ./configure && make all && ./ndiff -h && cp ndiff $GITHUB_WORKSPACE

    - name: Add ndiff to path
      run: echo "$GITHUB_WORKSPACE/ndiff" >> $GITHUB_PATH
      
    - name: check PATH
      run: echo $PATH 
    
    - name: configure
      run: ln -s gcc.mak Makefile

    - name: Install dependencies
      run: make all

    - name: Run check
      run: make check

    - name: Run distclean
      run: make distclean
