name: Makefile CI Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: brew ndiff
      run:  brew install ndiff
      
    - name: check ndiff
      run:  which ndiff && cp /home/linuxbrew/.linuxbrew/bin/ndiff . && ls $GITHUB_WORKSPACE && ./ndiff -h

    - name: Add ndiff to path
      run: echo "$GITHUB_WORKSPACE/ndiff" >> $GITHUB_PATH
      
    - name: check PATH
      run: echo $PATH 
    
    - name: configure
      run: ln -s gcc.mak Makefile

    - name: Install dependencies
      run: make all

    - name: Run check
      run: make check

    - name: Run distclean
      run: make distclean
