name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: brew ndiff
      run:  brew install ndiff

    - name: configure
      run: ln -s gcc.mak Makefile

    - name: Install dependencies
      run: make all

    - name: Run check
      run: make check

    - name: Run distclean
      run: make distclean
